import csv
import random

random.seed(42)

CATEGORIES = [
    "Plumbing", "HVAC", "Electrician", "Roofing", "Landscaping", "Lawn Care",
    "Tree Service", "Pest Control", "Cleaning Services", "Carpet Cleaning",
    "Window Cleaning", "Pressure Washing", "Painting", "Drywall", "Concrete",
    "Fencing", "Deck Building", "Masonry", "Insulation", "Gutter Cleaning",
    "Auto Repair", "Auto Body", "Auto Detailing", "Auto Glass", "Towing",
    "Tire Shop", "Oil Change", "Transmission Repair", "Muffler Shop",
    "Locksmith", "Moving", "Junk Removal", "Septic Services", "Well Drilling",
    "Pool Maintenance", "Chimney Sweep", "Garage Doors", "Welding",
    "Cabinet Making", "Hardwood Flooring", "Tile Installation", "Upholstery",
    "Appliance Repair", "Handyman", "General Contracting", "Renovations",
    "Window Installation", "Siding", "Stucco", "Paving/Asphalt",
    "Dog Grooming", "Boarding Kennel", "Dog Training", "Pet Sitting",
    "Veterinarian", "Pet Clinic", "Aquarium Service",
    "Massage Therapy", "Chiropractic", "Acupuncture", "Physiotherapy",
    "Personal Training", "Yoga Studio", "Barbershop", "Nail Salon",
    "Hair Salon", "Tattoo Parlour", "Tanning Salon", "Waxing Studio",
    "Bakery", "Catering", "Food Truck", "Meal Prep", "Personal Chef",
    "Tailoring/Alterations", "Dry Cleaning", "Laundromat", "Shoe Repair",
    "Bookkeeping", "Tax Preparation", "Notary", "Photography", "Videography",
    "Tutoring", "Music Lessons", "Daycare", "Senior Home Care",
    "Driving School", "Courier/Delivery", "Security Systems",
    "Small Engine Repair", "Lawn Mower Repair", "Bicycle Repair",
    "Computer Repair", "Phone Repair", "TV Repair", "Watch Repair",
    "Furniture Repair", "Piano Tuning", "Instrument Repair",
    "Printing Services", "Sign Making", "Embroidery", "Screen Printing",
    "Irrigation", "Hydroseeding", "Snow Removal", "Power Raking",
    "Duct Cleaning", "Mold Remediation", "Water Damage Restoration",
    "Glass & Mirror", "Blinds & Shutters", "Flooring Installation",
]

US_CITIES = [
    ("Huntsville", "Alabama"), ("Mobile", "Alabama"), ("Tuscaloosa", "Alabama"),
    ("Anchorage", "Alaska"), ("Fairbanks", "Alaska"),
    ("Flagstaff", "Arizona"), ("Tucson", "Arizona"), ("Mesa", "Arizona"),
    ("Yuma", "Arizona"), ("Peoria", "Arizona"),
    ("Fort Smith", "Arkansas"), ("Jonesboro", "Arkansas"), ("Conway", "Arkansas"),
    ("Bakersfield", "California"), ("Fresno", "California"), ("Stockton", "California"),
    ("Modesto", "California"), ("Riverside", "California"), ("Visalia", "California"),
    ("Santa Rosa", "California"), ("Oxnard", "California"), ("Chico", "California"),
    ("Colorado Springs", "Colorado"), ("Pueblo", "Colorado"), ("Fort Collins", "Colorado"),
    ("Greeley", "Colorado"), ("Boulder", "Colorado"), ("Grand Junction", "Colorado"),
    ("Bridgeport", "Connecticut"), ("New Haven", "Connecticut"), ("Hartford", "Connecticut"),
    ("Wilmington", "Delaware"), ("Dover", "Delaware"),
    ("Jacksonville", "Florida"), ("Tampa", "Florida"), ("Orlando", "Florida"),
    ("St. Petersburg", "Florida"), ("Hialeah", "Florida"), ("Tallahassee", "Florida"),
    ("Fort Lauderdale", "Florida"), ("Port St. Lucie", "Florida"), ("Pensacola", "Florida"),
    ("Gainesville", "Florida"), ("Cape Coral", "Florida"), ("Sarasota", "Florida"),
    ("Augusta", "Georgia"), ("Columbus", "Georgia"), ("Savannah", "Georgia"),
    ("Athens", "Georgia"), ("Macon", "Georgia"), ("Roswell", "Georgia"),
    ("Boise", "Idaho"), ("Nampa", "Idaho"), ("Meridian", "Idaho"), ("Idaho Falls", "Idaho"),
    ("Rockford", "Illinois"), ("Joliet", "Illinois"), ("Naperville", "Illinois"),
    ("Springfield", "Illinois"), ("Peoria", "Illinois"), ("Elgin", "Illinois"),
    ("Fort Wayne", "Indiana"), ("Evansville", "Indiana"), ("South Bend", "Indiana"),
    ("Carmel", "Indiana"), ("Fishers", "Indiana"), ("Bloomington", "Indiana"),
    ("Cedar Rapids", "Iowa"), ("Davenport", "Iowa"), ("Sioux City", "Iowa"),
    ("Wichita", "Kansas"), ("Overland Park", "Kansas"), ("Kansas City", "Kansas"),
    ("Topeka", "Kansas"), ("Olathe", "Kansas"),
    ("Lexington", "Kentucky"), ("Louisville", "Kentucky"), ("Bowling Green", "Kentucky"),
    ("Baton Rouge", "Louisiana"), ("Shreveport", "Louisiana"), ("Metairie", "Louisiana"),
    ("Lafayette", "Louisiana"), ("Lake Charles", "Louisiana"),
    ("Portland", "Maine"), ("Lewiston", "Maine"), ("Bangor", "Maine"),
    ("Baltimore", "Maryland"), ("Frederick", "Maryland"), ("Rockville", "Maryland"),
    ("Worcester", "Massachusetts"), ("Springfield", "Massachusetts"), ("Lowell", "Massachusetts"),
    ("Detroit", "Michigan"), ("Grand Rapids", "Michigan"), ("Warren", "Michigan"),
    ("Sterling Heights", "Michigan"), ("Lansing", "Michigan"), ("Ann Arbor", "Michigan"),
    ("Flint", "Michigan"), ("Dearborn", "Michigan"), ("Livonia", "Michigan"),
    ("Minneapolis", "Minnesota"), ("Saint Paul", "Minnesota"), ("Rochester", "Minnesota"),
    ("Duluth", "Minnesota"), ("Bloomington", "Minnesota"),
    ("Jackson", "Mississippi"), ("Gulfport", "Mississippi"), ("Biloxi", "Mississippi"),
    ("Kansas City", "Missouri"), ("Saint Louis", "Missouri"), ("Springfield", "Missouri"),
    ("Columbia", "Missouri"), ("Independence", "Missouri"),
    ("Billings", "Montana"), ("Missoula", "Montana"), ("Great Falls", "Montana"), ("Bozeman", "Montana"),
    ("Omaha", "Nebraska"), ("Lincoln", "Nebraska"), ("Bellevue", "Nebraska"),
    ("Las Vegas", "Nevada"), ("Henderson", "Nevada"), ("Reno", "Nevada"), ("Sparks", "Nevada"),
    ("Manchester", "New Hampshire"), ("Nashua", "New Hampshire"), ("Concord", "New Hampshire"),
    ("Newark", "New Jersey"), ("Jersey City", "New Jersey"), ("Paterson", "New Jersey"),
    ("Trenton", "New Jersey"), ("Camden", "New Jersey"),
    ("Albuquerque", "New Mexico"), ("Las Cruces", "New Mexico"), ("Santa Fe", "New Mexico"),
    ("Buffalo", "New York"), ("Rochester", "New York"), ("Yonkers", "New York"),
    ("Syracuse", "New York"), ("Albany", "New York"), ("Utica", "New York"),
    ("Charlotte", "North Carolina"), ("Raleigh", "North Carolina"), ("Greensboro", "North Carolina"),
    ("Durham", "North Carolina"), ("Winston-Salem", "North Carolina"), ("Fayetteville", "North Carolina"),
    ("Fargo", "North Dakota"), ("Bismarck", "North Dakota"),
    ("Cleveland", "Ohio"), ("Columbus", "Ohio"), ("Cincinnati", "Ohio"),
    ("Toledo", "Ohio"), ("Akron", "Ohio"), ("Dayton", "Ohio"), ("Youngstown", "Ohio"),
    ("Oklahoma City", "Oklahoma"), ("Tulsa", "Oklahoma"), ("Norman", "Oklahoma"),
    ("Eugene", "Oregon"), ("Salem", "Oregon"), ("Gresham", "Oregon"),
    ("Philadelphia", "Pennsylvania"), ("Pittsburgh", "Pennsylvania"), ("Allentown", "Pennsylvania"),
    ("Erie", "Pennsylvania"), ("Reading", "Pennsylvania"), ("Scranton", "Pennsylvania"),
    ("Providence", "Rhode Island"), ("Cranston", "Rhode Island"),
    ("Columbia", "South Carolina"), ("Charleston", "South Carolina"), ("North Charleston", "South Carolina"),
    ("Sioux Falls", "South Dakota"), ("Rapid City", "South Dakota"),
    ("Nashville", "Tennessee"), ("Memphis", "Tennessee"), ("Knoxville", "Tennessee"),
    ("Chattanooga", "Tennessee"), ("Clarksville", "Tennessee"),
    ("Houston", "Texas"), ("San Antonio", "Texas"), ("Dallas", "Texas"),
    ("Austin", "Texas"), ("Fort Worth", "Texas"), ("El Paso", "Texas"),
    ("Lubbock", "Texas"), ("Amarillo", "Texas"), ("Laredo", "Texas"),
    ("Corpus Christi", "Texas"), ("Abilene", "Texas"), ("Waco", "Texas"),
    ("Salt Lake City", "Utah"), ("West Valley City", "Utah"), ("Provo", "Utah"),
    ("Orem", "Utah"), ("Sandy", "Utah"),
    ("Burlington", "Vermont"), ("Montpelier", "Vermont"),
    ("Virginia Beach", "Virginia"), ("Norfolk", "Virginia"), ("Chesapeake", "Virginia"),
    ("Richmond", "Virginia"), ("Newport News", "Virginia"), ("Roanoke", "Virginia"),
    ("Lynchburg", "Virginia"), ("Charlottesville", "Virginia"),
    ("Seattle", "Washington"), ("Spokane", "Washington"), ("Tacoma", "Washington"),
    ("Vancouver", "Washington"), ("Bellevue", "Washington"), ("Olympia", "Washington"),
    ("Bellingham", "Washington"), ("Yakima", "Washington"),
    ("Charleston", "West Virginia"), ("Huntington", "West Virginia"),
    ("Milwaukee", "Wisconsin"), ("Madison", "Wisconsin"), ("Green Bay", "Wisconsin"),
    ("Kenosha", "Wisconsin"), ("Racine", "Wisconsin"), ("Appleton", "Wisconsin"),
    ("Cheyenne", "Wyoming"), ("Casper", "Wyoming"),
]

CA_CITIES = [
    ("Calgary", "Alberta"), ("Edmonton", "Alberta"), ("Red Deer", "Alberta"),
    ("Lethbridge", "Alberta"), ("Medicine Hat", "Alberta"), ("Grande Prairie", "Alberta"),
    ("Fort McMurray", "Alberta"), ("Airdrie", "Alberta"),
    ("Vancouver", "British Columbia"), ("Surrey", "British Columbia"),
    ("Burnaby", "British Columbia"), ("Kelowna", "British Columbia"),
    ("Abbotsford", "British Columbia"), ("Coquitlam", "British Columbia"),
    ("Langley", "British Columbia"), ("Kamloops", "British Columbia"),
    ("Nanaimo", "British Columbia"), ("Victoria", "British Columbia"),
    ("Prince George", "British Columbia"), ("Chilliwack", "British Columbia"),
    ("Maple Ridge", "British Columbia"), ("Vernon", "British Columbia"),
    ("Williams Lake", "British Columbia"),
    ("Winnipeg", "Manitoba"), ("Brandon", "Manitoba"), ("Steinbach", "Manitoba"),
    ("Moncton", "New Brunswick"), ("Fredericton", "New Brunswick"),
    ("Saint John", "New Brunswick"), ("Bathurst", "New Brunswick"),
    ("St. John's", "Newfoundland"), ("Corner Brook", "Newfoundland"),
    ("Yellowknife", "Northwest Territories"),
    ("Halifax", "Nova Scotia"), ("Dartmouth", "Nova Scotia"),
    ("Sydney", "Nova Scotia"), ("Truro", "Nova Scotia"),
    ("Barrie", "Ontario"), ("Brampton", "Ontario"), ("Bracebridge", "Ontario"),
    ("Brantford", "Ontario"), ("Cambridge", "Ontario"), ("Guelph", "Ontario"),
    ("Hamilton", "Ontario"), ("Kingston", "Ontario"), ("Kitchener", "Ontario"),
    ("London", "Ontario"), ("Markham", "Ontario"), ("Mississauga", "Ontario"),
    ("Niagara Falls", "Ontario"), ("Oakville", "Ontario"), ("Oshawa", "Ontario"),
    ("Ottawa", "Ontario"), ("Peterborough", "Ontario"), ("Sault Ste. Marie", "Ontario"),
    ("Sudbury", "Ontario"), ("Thunder Bay", "Ontario"), ("Timmins", "Ontario"),
    ("Vaughan", "Ontario"), ("Windsor", "Ontario"),
    ("Charlottetown", "Prince Edward Island"), ("Summerside", "Prince Edward Island"),
    ("Montreal", "Quebec"), ("Quebec City", "Quebec"), ("Laval", "Quebec"),
    ("Gatineau", "Quebec"), ("Longueuil", "Quebec"), ("Sherbrooke", "Quebec"),
    ("Saguenay", "Quebec"), ("Trois-Rivieres", "Quebec"),
    ("Regina", "Saskatchewan"), ("Saskatoon", "Saskatchewan"),
    ("Moose Jaw", "Saskatchewan"), ("Prince Albert", "Saskatchewan"),
    ("Whitehorse", "Yukon"),
]

FIRST_NAMES = [
    "Mike", "Dave", "John", "Bob", "Steve", "Chris", "Jim", "Tom", "Gary", "Rick",
    "Bill", "Scott", "Mark", "Jeff", "Brian", "Kevin", "Dan", "Paul", "Greg", "Larry",
    "Joe", "Frank", "Tony", "Pete", "Ray", "Brad", "Tim", "Ed", "Don", "Phil",
    "Sandy", "Karen", "Linda", "Donna", "Brenda", "Lisa", "Sharon", "Debbie", "Pam", "Cindy",
    "Maria", "Rosa", "Elena", "Teresa", "Carmen", "Angela", "Diana", "Gloria", "Sofia", "Ana",
    "Jean", "Nicole", "Michelle", "Stephanie", "Jennifer", "Amanda", "Jessica", "Melissa", "Crystal", "Amber",
    "Carlos", "Miguel", "Jose", "Luis", "Jorge", "Pedro", "Marco", "Rico", "Diego", "Roberto",
    "Wei", "Jin", "Mei", "Ying", "Jun", "Fang", "Hong", "Liang", "Ping", "Xiao",
    "Raj", "Priya", "Amir", "Fatima", "Hassan", "Ahmed", "Sara", "Omar", "Layla", "Nadia",
    "Andre", "Pierre", "Jacques", "Claude", "Luc", "Alain", "Gilles", "Yves", "Rene", "Denis",
    "Gord", "Wayne", "Dale", "Glen", "Keith", "Lance", "Brent", "Craig", "Troy", "Dwayne",
    "Earl", "Roy", "Floyd", "Clyde", "Merle", "Dwight", "Dale", "Travis", "Cody", "Blake",
    "Tamara", "Charlene", "Rhonda", "Wanda", "Shirley", "Glenda", "Patty", "Betty", "Norma", "Joyce",
    "Jerome", "Darius", "Darnell", "Marcus", "Jamal", "Tyrone", "DeShawn", "Malik", "Terrell", "Kendall",
    "Svetlana", "Olga", "Natasha", "Ivan", "Dmitri", "Boris", "Alexei", "Yuri", "Misha", "Sasha",
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Wilson", "Taylor",
    "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Young", "Lewis", "Walker",
    "Hall", "Allen", "King", "Wright", "Scott", "Green", "Baker", "Nelson", "Carter", "Mitchell",
    "Robinson", "Campbell", "Perez", "Evans", "Turner", "Collins", "Stewart", "Morris", "Rogers", "Reed",
    "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard",
    "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders",
    "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell",
    "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant",
    "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford", "Hamilton", "Graham", "Sullivan",
    "Wallace", "Woods", "Cole", "West", "Jordan", "Owens", "Reynolds", "Fisher", "Ellis", "Harrison",
    "Gibson", "McDonald", "Cruz", "Marshall", "Ortiz", "Gomez", "Murray", "Freeman", "Wells", "Webb",
    "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks", "Crawford", "Henry", "Boyd", "Mason",
    # Canadian-flavoured
    "Tremblay", "Gagnon", "Roy", "Cote", "Bouchard", "Gauthier", "Morin", "Lavoie", "Fortin", "Girard",
    "Belanger", "Ouellet", "Pelletier", "Leblanc", "Bergeron", "Lapointe", "Lafleur", "Robichaud", "Arsenault", "Chiasson",
    "Kowalski", "Novak", "Petrov", "Nguyen", "Pham", "Tran", "Kim", "Park", "Lee", "Chang",
    "Patel", "Shah", "Singh", "Sharma", "Kapoor", "Gupta", "Mehta", "Joshi", "Rao", "Reddy",
    "MacLeod", "MacDonald", "MacKenzie", "Campbell", "Fraser", "Grant", "Murray", "Stewart", "Reid", "Duncan",
    "Halverson", "Sorensen", "Larsen", "Andersen", "Nielsen", "Jensen", "Christensen", "Pedersen", "Olsen", "Hansen",
    "Korhonen", "Makinen", "Virtanen", "Laine", "Hamalainen", "Maki", "Nieminen", "Heikkinen", "Koskinen", "Jarvinen",
]

PREFIXES = [
    "A-1", "AAA", "Ace", "Action", "Active", "All Season", "All Star", "All Pro",
    "Alliance", "Alpine", "American", "Anchor", "Apple Valley", "Apex", "Arrow",
    "Atlas", "Bay Area", "Bayshore", "Bayview", "Big Sky", "Blue Ridge", "Blue Sky",
    "Bluewater", "Borderline", "Broad Street", "Brookside", "Budget", "Capital City",
    "Cascade", "Cedar", "Cedarwood", "Central", "Champion", "Clearwater", "Cliffside",
    "Coastal", "Colonial", "Colorado", "Columbia", "Community", "Compass", "Continental",
    "Copper Canyon", "Cornerstone", "Cottage Country", "Country", "Countryside",
    "Crossroads", "Crosstown", "Crown", "Crystal", "Cypress",
    "Desert", "Diamond", "Direct", "Dockside", "Dollar",
    "Eagle", "Eagle Ridge", "East Side", "Eastern", "Economy", "Elite",
    "Empire", "Evergreen", "Excel", "Express",
    "Family", "First Choice", "First Class", "Flagship", "Foothills", "Forest",
    "Fort", "Frontier", "Garden", "Gateway", "Gold Star", "Golden", "Golden Valley",
    "Grand", "Granite", "Great Plains", "Green", "Green Valley", "Gulf",
    "Harbour", "Harvest", "Heritage", "High Country", "High Desert", "High Plains",
    "Highland", "Hillcrest", "Hillside", "Hilltop", "Home Town", "Homestead",
    "Horizon", "Iron", "Ironwood", "Keystone", "Kings", "Lakeshore", "Lakeside",
    "Lakeview", "Lakewood", "Lakefront", "Liberty", "Lighthouse", "Lone Pine",
    "Lone Star", "Longview", "Magnolia", "Main Street", "Maple", "Maple Ridge",
    "Meadow", "Meadowbrook", "Metro", "Mid-Town", "Midland", "Midlands", "Midwest",
    "Millcreek", "Miramar", "Mission", "Modern", "Mountain", "Mountain High",
    "Mountain View", "Mountainview", "Mystic", "North", "North Country",
    "North Shore", "Northgate", "Northland", "Northside", "Northern",
    "Oak", "Oak Grove", "Oakridge", "Old Mill", "Old Town", "Olympic",
    "Open Range", "Pacific", "Palmetto", "Parkside", "Pineview", "Pinecrest",
    "Pioneer", "Plateau", "Port City", "Prairie", "Precision", "Premier",
    "Prime", "Pro", "Quality", "Quick", "Ridgecrest", "Ridgeline", "Riverbend",
    "Riverside", "Rocky Road", "Royal", "Sagebrush", "Seaside", "Silver Creek",
    "Skyline", "South Side", "Southern", "Southgate", "Summit", "Sunbelt",
    "Suncoast", "Sundance", "Sunrise", "Sunset", "Sunshine", "Superior",
    "Timberline", "Tidewater", "Township", "Trail", "Tri-City", "Tri-State",
    "United", "Uptown", "Urban", "Valley", "Valley View", "Village", "Westcoast",
    "Westside", "White Mountain", "Willow", "Willowbrook", "Willow Creek", "Woodland",
]

SUFFIXES_BY_CAT = {
    "Plumbing": ["Plumbing", "Plumbing & Drain", "Plumbing Services", "Plumbing Co.", "Rooter"],
    "HVAC": ["HVAC", "Heating & Cooling", "Heating & Air", "Climate Control", "Air Systems"],
    "Electrician": ["Electric", "Electrical", "Electrical Services", "Electrical Co.", "Wiring"],
    "Roofing": ["Roofing", "Roofing Co.", "Roofing & Siding", "Roof Repair"],
    "Landscaping": ["Landscaping", "Lawn & Garden", "Landscape Services", "Grounds Care"],
    "Lawn Care": ["Lawn Care", "Lawn Service", "Lawn Maintenance", "Mowing"],
    "Tree Service": ["Tree Service", "Tree Care", "Tree & Stump", "Arborist"],
    "Pest Control": ["Pest Control", "Exterminators", "Pest Services", "Bug & Rodent Control"],
    "Cleaning Services": ["Cleaning", "Cleaning Co.", "Cleaning Services", "Clean Team", "Maids"],
    "Carpet Cleaning": ["Carpet Cleaning", "Carpet Care", "Floor Cleaning", "Steam Cleaning"],
    "Window Cleaning": ["Window Cleaning", "Window Wash", "Window Care"],
    "Pressure Washing": ["Pressure Washing", "Power Wash", "Power Washing Co."],
    "Painting": ["Painting", "Painting Co.", "Paint & Stain", "Painting Services"],
    "Drywall": ["Drywall", "Drywalling", "Drywall & Plastering"],
    "Concrete": ["Concrete", "Concrete Co.", "Concrete & Paving"],
    "Fencing": ["Fencing", "Fence & Gate", "Fence Co."],
    "Deck Building": ["Decks & Patios", "Deck Builders", "Deck Construction"],
    "Masonry": ["Masonry", "Stonework", "Masonry & Stone"],
    "Insulation": ["Insulation", "Insulation Co.", "Spray Foam"],
    "Gutter Cleaning": ["Gutters", "Gutter Cleaning", "Eavestrough"],
    "Auto Repair": ["Auto Repair", "Auto Service", "Automotive", "Auto Works", "Car Care"],
    "Auto Body": ["Auto Body", "Body Shop", "Collision Repair", "Auto Body Works"],
    "Auto Detailing": ["Auto Detail", "Auto Detailing", "Car Wash & Detail", "Detail Shop"],
    "Auto Glass": ["Auto Glass", "Glass & Windshield", "Windshield Repair"],
    "Towing": ["Towing", "Tow & Recovery", "Roadside Towing"],
    "Tire Shop": ["Tire & Auto", "Tire Service", "Tires & Wheels"],
    "Oil Change": ["Quick Lube", "Oil & Filter", "Oil Change"],
    "Transmission Repair": ["Transmission", "Transmission & Auto", "Trans Repair"],
    "Muffler Shop": ["Muffler & Exhaust", "Exhaust & Brakes", "Muffler Shop"],
    "Locksmith": ["Locksmith", "Lock & Key", "Security & Locks"],
    "Moving": ["Moving", "Moving Co.", "Movers", "Moving & Storage"],
    "Junk Removal": ["Junk Removal", "Hauling & Disposal", "1-800-Junk Alternative", "Rubbish Removal"],
    "Septic Services": ["Septic", "Septic & Drain", "Pumping & Septic"],
    "Well Drilling": ["Well Drilling", "Water Well Service"],
    "Pool Maintenance": ["Pool Service", "Pool & Spa", "Pool Care"],
    "Chimney Sweep": ["Chimney", "Chimney Sweep", "Fireplace & Chimney"],
    "Garage Doors": ["Garage Doors", "Overhead Doors", "Garage Door Service"],
    "Welding": ["Welding", "Welding & Fabrication", "Metal Works"],
    "Cabinet Making": ["Cabinetry", "Cabinet Co.", "Custom Cabinets"],
    "Hardwood Flooring": ["Hardwood Floors", "Wood Flooring", "Floor Refinishing"],
    "Tile Installation": ["Tile & Stone", "Tile Installation", "Tile Works"],
    "Upholstery": ["Upholstery", "Auto & Furniture Upholstery", "Reupholstering"],
    "Appliance Repair": ["Appliance Repair", "Appliance Service", "Fix-It Appliances"],
    "Handyman": ["Handyman", "Handyman Services", "Fix-It Services", "Home Repair"],
    "General Contracting": ["Construction", "General Contracting", "Building & Renovation"],
    "Renovations": ["Renovations", "Home Renovations", "Remodeling"],
    "Window Installation": ["Windows & Doors", "Window Replacement", "Window World"],
    "Siding": ["Siding & Trim", "Vinyl Siding", "Siding Installation"],
    "Stucco": ["Stucco & Plaster", "Stucco Finishing"],
    "Paving/Asphalt": ["Paving", "Asphalt & Sealing", "Paving Co."],
    "Dog Grooming": ["Dog Grooming", "Pet Grooming", "Grooming Salon"],
    "Boarding Kennel": ["Boarding Kennel", "Pet Lodge", "Dog Boarding"],
    "Dog Training": ["Dog Training", "Canine Training", "K9 Academy"],
    "Pet Sitting": ["Pet Sitting", "Pet Care", "In-Home Pet Care"],
    "Veterinarian": ["Veterinary", "Animal Clinic", "Pet Clinic", "Animal Hospital"],
    "Pet Clinic": ["Animal Care", "Pet Health", "Veterinary Services"],
    "Aquarium Service": ["Aquarium Service", "Fish Tank Maintenance"],
    "Massage Therapy": ["Massage Therapy", "Massage & Wellness", "Therapeutic Massage"],
    "Chiropractic": ["Chiropractic", "Chiro & Wellness", "Spine & Joint Care"],
    "Acupuncture": ["Acupuncture", "Holistic Health", "Acupuncture & Wellness"],
    "Physiotherapy": ["Physiotherapy", "Physical Therapy", "Rehab & Physio"],
    "Personal Training": ["Personal Training", "Fitness Training", "Private Training"],
    "Yoga Studio": ["Yoga Studio", "Yoga & Wellness", "Hot Yoga"],
    "Barbershop": ["Barbershop", "Barber", "Hair & Shave"],
    "Nail Salon": ["Nail Salon", "Nails & Spa", "Nail Studio"],
    "Hair Salon": ["Hair Salon", "Hair Studio", "Salon & Spa"],
    "Tattoo Parlour": ["Tattoo", "Tattoo & Piercing", "Ink Studio"],
    "Tanning Salon": ["Tanning Salon", "Sun Studio", "Bronze & Glow"],
    "Waxing Studio": ["Wax Studio", "Waxing & Threading"],
    "Bakery": ["Bakery", "Baked Goods", "Bakehouse", "Pastries"],
    "Catering": ["Catering", "Catering Co.", "Event Catering", "Food & Catering"],
    "Food Truck": ["Food Truck", "Mobile Kitchen", "Street Eats"],
    "Meal Prep": ["Meal Prep", "Healthy Meals", "Meal Delivery"],
    "Personal Chef": ["Personal Chef", "Private Chef", "Chef Services"],
    "Tailoring/Alterations": ["Alterations", "Tailoring", "Custom Tailoring", "Sewing & Alterations"],
    "Dry Cleaning": ["Dry Cleaning", "Dry Cleaners", "Cleaners & Tailoring"],
    "Laundromat": ["Laundromat", "Coin Laundry", "Wash & Fold"],
    "Shoe Repair": ["Shoe Repair", "Cobbler", "Shoe & Leather Repair"],
    "Bookkeeping": ["Bookkeeping", "Accounting Services", "Books & Taxes"],
    "Tax Preparation": ["Tax Services", "Tax Prep", "Income Tax"],
    "Notary": ["Notary Services", "Notary Public"],
    "Photography": ["Photography", "Photo Studio", "Portraits & Events"],
    "Videography": ["Videography", "Video Productions", "Event Video"],
    "Tutoring": ["Tutoring", "Learning Centre", "Academic Tutoring"],
    "Music Lessons": ["Music Lessons", "Music School", "Piano & Guitar Lessons"],
    "Daycare": ["Daycare", "Child Care", "Family Daycare"],
    "Senior Home Care": ["Senior Care", "Home Care", "Elder Care Services"],
    "Driving School": ["Driving School", "Driver Training", "Auto School"],
    "Courier/Delivery": ["Courier", "Delivery Service", "Local Courier"],
    "Security Systems": ["Security", "Security Systems", "Home Security"],
    "Small Engine Repair": ["Small Engine Repair", "Engine & Equipment Repair"],
    "Lawn Mower Repair": ["Mower Repair", "Small Engine & Mower"],
    "Bicycle Repair": ["Bike Repair", "Cycle Shop", "Bicycle Service"],
    "Computer Repair": ["Computer Repair", "PC & Mac Repair", "Tech Repair"],
    "Phone Repair": ["Phone Repair", "Cell Phone Fix", "Screen Repair"],
    "TV Repair": ["TV Repair", "Electronics Repair", "Screen & TV Fix"],
    "Watch Repair": ["Watch Repair", "Timepiece Repair"],
    "Furniture Repair": ["Furniture Repair", "Furniture Restoration"],
    "Piano Tuning": ["Piano Tuning", "Piano Service"],
    "Instrument Repair": ["Instrument Repair", "Music Equipment Repair"],
    "Printing Services": ["Printing", "Print Shop", "Copy & Print"],
    "Sign Making": ["Signs & Graphics", "Sign Shop", "Signage"],
    "Embroidery": ["Embroidery & Monogram", "Custom Embroidery"],
    "Screen Printing": ["Screen Printing", "Custom Tees", "T-Shirt Printing"],
    "Irrigation": ["Irrigation", "Sprinkler Systems", "Irrigation & Lawn"],
    "Hydroseeding": ["Hydroseeding", "Lawn & Hydroseed"],
    "Snow Removal": ["Snow Removal", "Snow Plowing", "Winter Services"],
    "Power Raking": ["Power Raking", "Dethatching", "Lawn Aeration"],
    "Duct Cleaning": ["Duct Cleaning", "Air Duct Cleaning", "HVAC Duct Service"],
    "Mold Remediation": ["Mold Remediation", "Mold & Moisture Control"],
    "Water Damage Restoration": ["Water Damage", "Flood Restoration", "Restoration Services"],
    "Glass & Mirror": ["Glass & Mirror", "Custom Glass", "Mirror & Glass"],
    "Blinds & Shutters": ["Blinds & Shutters", "Window Coverings", "Custom Blinds"],
    "Flooring Installation": ["Flooring", "Floor Installation", "Flooring Solutions"],
}

NOTES = [
    "Facebook page only.", "Google Maps listing only.", "Word-of-mouth only.",
    "Yelp listing only.", "Craigslist ads.", "No digital presence whatsoever.",
    "Yellow Pages listing.", "Kijiji ads only.", "Phone book listing.",
    "Door-to-door flyers.", "Flyers and referrals.", "Instagram only.",
    "Nextdoor referrals only.", "Yard signs only.", "Lawn signs and referrals.",
    "HomeStars profile only.", "Angie's List profile.", "Postcards and flyers.",
    "Old Yellow Pages ad.", "Jane App only. No own website.",
    "Facebook check-ins.", "Facebook group only.", "Farmers market vendor only.",
    "Walk-in traffic only.", "Phone orders only.", "No social media. No web.",
    "Existing site broken since 2018.", "Old Tripod site, not maintained.",
    "Business card and referrals only.", "Local newspaper ads only.",
    "Radio ads, no web.", "Lettered truck, no site.", "Thumbtack profile only.",
    "Listed on HomeAdvisor only.", "Houzz profile. No own website.",
    "The Knot listed but no own site.", "Listed on Bark.com only.",
    "Yelp + Facebook. No website.", "Google Business profile only.",
    "In business 20+ years. No web presence.", "Family-run shop. Facebook only.",
    "Referrals and repeat customers only.", "Chamber of Commerce directory only.",
]

def area_code(city, state):
    # Rough mapping for realism — not exhaustive
    codes = {
        "Alberta": ["403", "780", "587"],
        "British Columbia": ["604", "778", "250"],
        "Manitoba": ["204", "431"],
        "New Brunswick": ["506"],
        "Newfoundland": ["709"],
        "Northwest Territories": ["867"],
        "Nova Scotia": ["902"],
        "Ontario": ["416", "647", "905", "519", "613", "705", "807"],
        "Prince Edward Island": ["902"],
        "Quebec": ["514", "438", "450", "418", "819"],
        "Saskatchewan": ["306", "639"],
        "Yukon": ["867"],
        "Alabama": ["205", "251", "256", "334"],
        "Alaska": ["907"],
        "Arizona": ["480", "520", "602", "623", "928"],
        "Arkansas": ["479", "501", "870"],
        "California": ["209", "213", "310", "408", "415", "510", "559", "562", "619", "661", "714", "760", "805", "818", "951"],
        "Colorado": ["303", "719", "720", "970"],
        "Connecticut": ["203", "475", "860"],
        "Delaware": ["302"],
        "Florida": ["239", "305", "321", "352", "386", "407", "561", "727", "772", "786", "813", "850", "863", "904", "941", "954"],
        "Georgia": ["229", "404", "470", "478", "678", "706", "762", "770", "912"],
        "Idaho": ["208"],
        "Illinois": ["217", "224", "309", "312", "331", "618", "630", "708", "773", "815", "847"],
        "Indiana": ["219", "260", "317", "463", "574", "765", "812"],
        "Iowa": ["319", "515", "563", "641", "712"],
        "Kansas": ["316", "620", "785", "913"],
        "Kentucky": ["270", "364", "502", "606", "859"],
        "Louisiana": ["225", "318", "337", "504", "985"],
        "Maine": ["207"],
        "Maryland": ["240", "301", "410", "443"],
        "Massachusetts": ["339", "351", "413", "508", "617", "774", "781", "857", "978"],
        "Michigan": ["231", "248", "269", "313", "517", "586", "616", "734", "810", "906", "947", "989"],
        "Minnesota": ["218", "320", "507", "612", "651", "763", "952"],
        "Mississippi": ["228", "601", "662", "769"],
        "Missouri": ["314", "417", "573", "636", "660", "816"],
        "Montana": ["406"],
        "Nebraska": ["308", "402", "531"],
        "Nevada": ["702", "725", "775"],
        "New Hampshire": ["603"],
        "New Jersey": ["201", "551", "609", "732", "848", "856", "862", "908", "973"],
        "New Mexico": ["505", "575"],
        "New York": ["212", "315", "347", "516", "518", "585", "607", "631", "646", "716", "718", "845", "914", "917"],
        "North Carolina": ["252", "336", "704", "743", "828", "910", "919", "980", "984"],
        "North Dakota": ["701"],
        "Ohio": ["216", "234", "283", "330", "380", "419", "440", "513", "567", "614", "740", "937"],
        "Oklahoma": ["405", "539", "580", "918"],
        "Oregon": ["458", "503", "541", "971"],
        "Pennsylvania": ["215", "267", "272", "412", "484", "570", "610", "717", "724", "814", "878"],
        "Rhode Island": ["401"],
        "South Carolina": ["803", "843", "854", "864"],
        "South Dakota": ["605"],
        "Tennessee": ["423", "615", "629", "731", "865", "901", "931"],
        "Texas": ["210", "214", "254", "281", "325", "346", "361", "409", "430", "432", "469", "512", "682", "713", "726", "737", "806", "817", "830", "832", "903", "915", "936", "940", "956", "972", "979"],
        "Utah": ["385", "435", "801"],
        "Vermont": ["802"],
        "Virginia": ["276", "434", "540", "571", "703", "757", "804"],
        "Washington": ["206", "253", "360", "425", "509", "564"],
        "West Virginia": ["304", "681"],
        "Wisconsin": ["262", "414", "534", "608", "715", "920"],
        "Wyoming": ["307"],
    }
    options = codes.get(state, ["555"])
    return random.choice(options)

def phone(city, state):
    ac = area_code(city, state)
    return f"({ac}) {random.randint(200,999)}-{random.randint(1000,9999)}"

def make_name(category):
    prefix = random.choice(PREFIXES)
    suffixes = SUFFIXES_BY_CAT.get(category, [category])
    suffix = random.choice(suffixes)
    return f'"{prefix} {suffix}"'

def make_contact():
    first = random.choice(FIRST_NAMES)
    last = random.choice(LAST_NAMES)
    if random.random() < 0.08:
        return f"Dr. {first} {last}"
    return f"{first} {last}"

def main():
    all_cities = [(c, s, "USA") for c, s in US_CITIES] + [(c, s, "Canada") for c, s in CA_CITIES]

    rows = []
    seen = set()
    attempts = 0
    while len(rows) < 3000 and attempts < 30000:
        attempts += 1
        category = random.choice(CATEGORIES)
        city, state, country = random.choice(all_cities)
        name = make_name(category)
        key = (name, city)
        if key in seen:
            continue
        seen.add(key)
        contact = make_contact()
        ph = phone(city, state)
        note = random.choice(NOTES)
        rows.append([name, category, city, state, country, ph, contact, note])

    output_path = "/home/user/Portfolio-OS/client-list-no-website.csv"
    with open(output_path, "a", newline="") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        writer.writerows(rows)

    print(f"Done — appended {len(rows)} rows.")

if __name__ == "__main__":
    main()
